# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "geerlingguy/centos7"
    jenkins.vm.hostname = "jenkins-srv-centos7"

    jenkins.vm.network :private_network, ip: "192.168.56.17"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins-srv-centos7"
      vb.memory = 2048
      vb.cpus = 2
    end

    jenkins.vm.provision :shell do |shell|
      shell.env = { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
      shell.path = "install_jenkins.sh"
    end
  end
end
  